### ISSUE TITLE
Want to do Traditional Chinese Translation

### ISSUE THREAD

**Issue by jh961202** [Tachiorz/MS2-English-Translation#52]
Hello Tachiorz, I'm a Mapler from Taiwan. First of all, I'd like to thank you for your effort. It's awesome!
Since I also play MS2, I want to help the translation. But I don't understand Korean, instead, I want to translate it to Traditional Chinese based on your English translation.
If I can do any help, please let me know. Thanks!
(Forked)

**Comment by Tachiorz** [comment]
Translation was done with free MS translator https://www.microsoft.com/en-us/translator/translatorapi.aspx (and it's crap)
Try to find free or cheap service to translate directly from kr
